jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Ruby and install dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler
          bundle install

      # Install NVM and Node.js v17.9.1
      - name: Install NVM and Node.js v17.9.1
        run: |
          # Install NVM
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Source nvm
          
          # Install Node.js v17.9.1
          nvm install 17.9.1
          nvm use 17.9.1  # Make sure Node.js 17.9.1 is being used
          
          # Verify Node.js installation
          node -v  # Check Node version to ensure correct installation
          nvm alias default 17.9.1  # Set as the default Node.js version

      # Ensure SSH known hosts are updated to avoid host key issues
      - name: Remove old SSH key from known_hosts
        run: |
          ssh-keygen -R "<your-server-ip-or-hostname>"

      # Deploy using Capistrano
      - name: Deploy using Capistrano
        run: |
          # Ensure NVM is sourced during the deployment
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Source nvm for deployment
          nvm install 17.9.1  # Ensure Node.js v17.9.1 is installed
          nvm use 17.9.1  # Make it the active version
          bundle exec cap staging deploy
