name: CI/CD Deployment

on:
  push:
    branches: 
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Ruby and install dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      # Step 3: Set up SSH keys for deployment to EC2
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 4: Deploy using Capistrano (and install NVM + Node.js on EC2)
      - name: Deploy to EC2 and Install NVM + Node.js
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            # Install NVM if not already installed
            if ! command -v nvm &> /dev/null
            then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
              source ~/.bashrc
            fi

            # Install Node.js version 17.9.1 using NVM (if not already installed)
            if ! nvm ls 17.9.1 &> /dev/null
            then
              nvm install 17.9.1
            fi

            # Set Node.js version 17.9.1 to be used
            nvm use 17.9.1

            # Ensure npm is installed and up-to-date
            npm install -g npm

            # Run the Capistrano deploy command
            cd /path/to/your/project/directory
            bundle exec cap staging deploy
          EOF

