name: CI/CD Deployment

on:
  push:
    branches: 
      - staging
      
  # pull_request:
  #   branches: 
  #     - main
  #     - master
  #     - github_actions

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Ruby and install dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      # Step 3: Set up SSH keys for deployment to EC2
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
      # # Step 3: Install Node.js version 17.9.1 using the custom script
      # - name: Install Node.js 17.9.1
      #   run: |
      #     chmod +x ./scripts.sh # Make the script executable
      #     ./scripts.sh          # Run the script

      # Step 3: Install Node.js version 17.9.1 using the custom script
      - name: Install Node.js 17.9.1
        run: |
          sudo apt install nodejs npm -y
      # Step 4: Install NVM and Node.js v17.9.1
      - name: Install NVM and Node.js v17.9.1
        run: |
          # Install NVM
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          
          # Source nvm
          source ~/.bashrc
          
      #Step 5 Remove the old SSH key from known_hosts (in case of SSH mismatch)
      - name: Remove old SSH key from known_hosts
        run: |
          ssh-keygen -R "18.189.30.188"

      # Step 6: Deploy using Capistrano
      - name: Deploy to EC2
        run: |
          # Ensure NVM is sourced during the deployment
          source ~/.bashrc
          
          # Install and use Node.js v17.9.1
          nvm install 17.9.1
          nvm use 17.9.1

          # Deploy using Capistrano
          bundle exec cap staging deploy