name: Deploy to EC2 using Capistrano

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 1: Set up SSH keys and known hosts
    - name: Set up SSH keys and known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host github.com\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    # Step 2: Start SSH agent and add the private key
    - name: Start SSH agent and add private key
      run: |
        # Start the SSH agent
        eval $(ssh-agent -s)
        
        # Clear any previously added keys
        ssh-add -D
        
        # Add the correct private key
        ssh-add ~/.ssh/id_rsa

    # Step 3: Install Ruby, Bundler, Node.js, etc.
    - name: Install Ruby, Bundler, Node.js dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full build-essential libssl-dev libreadline-dev zlib1g-dev nodejs npm ruby-bundler curl

    # Step 4: Install Bundler, Capistrano, and NVM
    - name: Install Bundler, Capistrano and NVM
      run: |
        gem install bundler
        export PATH="$HOME/.gem/ruby/3.2.0/bin:$PATH"
        bundle install
        gem install capistrano -v 3.16.0

    # Step 5: Install Node.js via NVM
    - name: Install NVM and Node.js
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
        nvm install 17.9.1
        npm install pm2@latest -g

    # Step 6: Deploy using Capistrano
    - name: Deploy with Capistrano
      run: |
        export PATH="$HOME/.gem/ruby/3.2.0/bin:$PATH"
        bundle exec cap staging deploy
      env:
        CAPISTRANO_SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        CAPISTRANO_HOST: ${{ secrets.EC2_HOST }}
