name: Deploy to EC2 using Capistrano

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH keys and known hosts
    - name: Set up SSH keys and known hosts
      run: |
        # Create the SSH directory if it doesn't exist
        mkdir -p ~/.ssh

        # Save the private SSH key from GitHub Secrets
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Disable StrictHostKeyChecking (for testing purposes)
        echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

        # Add the EC2 instance to known_hosts to prevent host key mismatch
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    # Step 3: Install required dependencies (e.g., Ruby, Bundler, Capistrano)
    - name: Install Ruby and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full
        sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev
        gem install bundler
        bundle install

    # Step 4: Set up Capistrano (if not already installed)
    - name: Install Capistrano
      run: |
        gem install capistrano

    # Step 5: Deploy to EC2 server using Capistrano
    - name: Deploy to EC2 Server using Capistrano
      run: |
        cap staging deploy
      env:
        CAPISTRANO_SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        CAPISTRANO_HOST: ${{ secrets.EC2_HOST }}
