name: CI/CD Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Install Ruby and Bundler using apt and gem
      - name: Install Ruby and Bundler
        run: |
          # Update package list and install ruby (for installing bundler later)
          sudo apt-get update
          sudo apt-get install -y ruby-full

          # Install Bundler via gem (Ruby's package manager)
          sudo gem install bundler

          # Verify Bundler installation
          bundle --version

      # Step 3: Install Node.js and npm using NVM
      - name: Install Node.js using NVM
        run: |
          # Install NVM if not already installed
          if ! command -v nvm &> /dev/null
          then
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
          fi

          # Source NVM
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

          # Install Node.js version 17.9.1
          nvm install 17.9.1
          nvm use 17.9.1

          # Install a compatible version of npm
          npm install -g npm@8.11.0

      # Step 4: Set up SSH keys for deployment to EC2
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 5: Ensure project directory exists and deploy
      - name: Ensure project directory exists and deploy
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Ensure the apps directory exists
            mkdir -p /home/ubuntu/apps/client_api/

            # Ensure the project directory exists
            PROJECT_DIR="/home/ubuntu/apps/your-project-directory"
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Project directory not found, creating..."
              mkdir -p "$PROJECT_DIR"
            fi

            # Ensure NVM is installed and sourced properly
            if ! command -v nvm &> /dev/null
            then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            fi
            
            # Source nvm to ensure it's available in the current session
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            # Install Node.js version 17.9.1 using NVM
            if ! nvm ls 17.9.1 &> /dev/null
            then
              nvm install 17.9.1
            fi

            # Set Node.js version 17.9.1 to be used
            nvm use 17.9.1

            # Downgrade npm to a compatible version with Node.js 17.9.1
            npm install -g npm@8.11.0

            # Ensure Bundler is installed
            if ! command -v bundle &> /dev/null
            then
              echo "Bundler not found, installing..."
              sudo gem install bundler
            fi

            # Verify Bundler installation
            bundle --version

            # Navigate to the project directory
            cd $PROJECT_DIR

            # Run the Capistrano deploy command
            bundle exec cap staging deploy
          EOF
