name: CI/CD Deployment

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Ruby and install dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      # Step 3: Set up SSH keys for deployment to EC2
      - name: Set up SSH keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Step 4: Deploy to EC2, create apps directory, and install NVM + Node.js
      - name: Deploy to EC2, create apps directory, and install NVM + Node.js
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            # Create the apps directory if it doesn't exist
            # mkdir -p /home/ubuntu/apps//client_api/

            # Ensure NVM is installed and sourced properly
            if ! command -v nvm &> /dev/null
            then
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
            fi
            
            # Source nvm to ensure it's available in the current session
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

            # Install Node.js version 17.9.1 using NVM
            if ! nvm ls 17.9.1 &> /dev/null
            then
              nvm install 17.9.1
            fi

            # Set Node.js version 17.9.1 to be used
            nvm use 17.9.1

            # Downgrade npm to a compatible version with Node.js 17.9.1
            npm install -g npm@8.11.0

            # Ensure project directory exists
            PROJECT_DIR="/home/ubuntu/apps/your-project-directory"
            if [ ! -d "$PROJECT_DIR" ]; then
              echo "Error: Project directory $PROJECT_DIR not found"
              exit 1
            fi

            # Navigate to the project directory and run the Capistrano deploy command
            cd $PROJECT_DIR
            bundle exec cap staging deploy
          EOF
