name: Deploy to EC2 using Capistrano and Git Pull

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH keys and known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo -e "Host *\n  StrictHostKeyChecking no\n  UserKnownHostsFile=/dev/null" >> ~/.ssh/config
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Start SSH Agent and add private key
      run: |
        eval $(ssh-agent -s) # Start SSH Agent
        ssh-add ~/.ssh/id_rsa # Add the private key

    - name: Install Ruby, Bundler, and Node.js dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ruby-full build-essential libssl-dev libreadline-dev zlib1g-dev nodejs npm ruby-bundler curl

    - name: Set up local gem installation directory
      run: |
        echo "gem: --user-install" >> ~/.gemrc
        export PATH="$(ruby -e 'puts Gem.user_dir')/bin:$PATH"
        echo $PATH

    - name: Install Bundler and Capistrano
      run: |
        gem install bundler
        export PATH="$HOME/.gem/ruby/3.2.0/bin:$PATH"
        bundle config set --local path 'vendor/bundle'
        bundle install
        gem install capistrano -v 3.16.0

    - name: Install NVM, Node.js, and PM2
      run: |
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
        export NVM_DIR="$HOME/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # Source NVM
        nvm --version  # Check nvm version
        nvm install 17.9.1
        nvm use 17.9.1
        node -v  # Verify Node.js version
        npm -v   # Verify npm version
        npm install pm2@latest -g

    - name: Install Rails app
      run: |
        gem install rails -v 8.0.0

    - name: Deploy to EC2 Server using Capistrano
      run: |
        export PATH="$HOME/.gem/ruby/3.2.0/bin:$PATH"
        bundle exec cap staging deploy
      env:
        CAPISTRANO_SSH_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        CAPISTRANO_HOST: ${{ secrets.EC2_HOST }}
